version: "3.8"
services:
  api:
    build: ./api/
    ports: 
      - "9090:9090"
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  etherpad:
    image: ./api/etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
