version: "3.8"
services:
  mywww:
    build:
      context: ./front/
      dockerfile: Dockerfile
      target: prod
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./server-confs:/server-confs  
      - ./letsencrypt:/etc/letsencrypt  
    environment:
      - MULTISITE=no     
      - SERVER_NAME=fleroyvm.diverse-team.fr #pad.diverse-team.fr # phpmyadmin.diverse-team.fr          
      - SERVE_FILES=yes
      - USE_FAIL2BAN=no
      - DISABLE_DEFAULT_SERVER=no
    # Transmission de l'IP publique vers les containers
      - PROXY_REAL_IP=yes
        #- MAX_CLIENT_SIZE=100m
        #- USE_ANTIBOT=captcha
# Configuration de letencrypt
      - AUTO_LETS_ENCRYPT=yes
# redirect du 80 vers 443 automatique
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_LIMIT_REQ=no
# Désactivation http2
      - HTTP2=no
  api:  
    image: quarkus/code-with-quarkus-jvm
    ports: 
      - "8080"  
    environment: 
      - MYSQL_URI=jdbc:mysql://db:3306
    depends_on:
      - db
      - etherpad
      - mail
    deploy:
      restart_policy:
        condition: on-failure    
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  etherpad:
    image: etherpad/etherpad:stable
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
